### ISSUE TITLE
Code problem.

### ISSUE THREAD

**Issue by LEEYK1995** [VoiceBeer/MS-MDA#1]
你好，我发现您代码中DANN的相关方法存在一些问题，然后我自己修改了一下却达不到论文中的效果，请问是否可以修改一下？

**Comment by VoiceBeer** [comment]
你好，感谢您的提问，抱歉没有及时答复。

关于DANN，我个人使用中确实存在问题，因此论文里没有放入对比。这个代码全部是基于 [jindongwang/transferlearning](https://github.com/jindongwang/transferlearning) 这个repo修改的。现在他们的repo中整体的架构已经改了很多，建议您如果想复现DANN的话可以参考他们的repo。
