### ISSUE TITLE
关于准确率

### ISSUE THREAD

**Issue by ameiggychu** [VoiceBeer/MS-MDA#10]
作者大大你好~我用seed数据集跑了你的实验，是分了三个1、2、3文件夹，把每个人不同期的mat文件放进去，但是跑出来cross-sub只有68，cross-sess是79，7是我放的数据集形式不对还是什么可能的原因导致的哇

**Comment by VoiceBeer** [comment]
哈喽，这个问题在[readme里有讲](https://github.com/VoiceBeer/MS-MDA#loso-experiments)，如果想复现论文里的结果，只需要把代码里对每个被试的遍历改成对只把最后一个被试当作target就行

**Comment by ameiggychu** [comment]
你好，忘记回复了，这个问题已经解决了，感谢你的回复~祝你生活愉快！

**Comment by VoiceBeer** [comment]
@ameiggychu 也祝你一切顺利！:relaxed:
