### ISSUE TITLE
关于损失函数

### ISSUE THREAD

**Issue by zmxnancy123** [VoiceBeer/MS-MDA#11]
哈喽，我想问一下代码中使用mmd_linear时损失很小也很稳定，但是我换成您代码里的mmd或者CORAL损失就会不稳定而且偏大，这是为什么啊，还想问问您关于目标域是否参与训练这个问题。

**Comment by VoiceBeer** [comment]
哈喽，mmd_linear是简化版的mmd，相比来说肯定会更加简单，但是会不够准确和不够精确。不过我倒是没试过不同loss的结果，你要是感兴趣的话可以试试，可能对于eeg数据来说简单点会更好。关于第二个问题，在训练过程中，目标域是参与训练的，不过仅提供目标域的分布，无标签，关于这个你可以看一下[王晋东老师的解释](
https://www.zhihu.com/question/68275921/answer/2034667107)。

**Comment by zmxnancy123** [comment]
好的好的，感谢您的回答！

**Comment by VoiceBeer** [comment]
@zmxnancy123 不客气不客气，欢迎继续提问，这个issue我先close了 :>

**Comment by zmxnancy123** [comment]
你好，我想问一下整个实验是训练迭代一定的次数后进行测试，然后选取测试结果最好的一次作为最终结果，感觉有点像是只有训练集和验证集，并没有单独划分不参与训练的测试集。测试的时间应该是很短的，但这个需要跑完所有才出结果是因为将训练和测试放在一起了吗？我在改了模型后出现不同的被试相同的准确率，这是被允许的吗，还是网络出现了问题

**Comment by VoiceBeer** [comment]
你这段话里有很多问题，可以分点一个一个问。

1. 还是上面提到过的，领域自适应目标域样本参与训练，标签仅在测试的时候计算acc，因此目标域为测试集，训练过程中没有验证集
2. 看主代码逻辑，训练完后才测试
3. 不同的背试相同的准确率是指目标背试还是源被试，相同准确率是指什么。具体一点，可以放log。相同准确率是存在出现的可能，你可以看具体的预测值，如果两个被试的预测值完全一样导致的一样的准确率，那可能有点问题；如果预测值都是不一样的，只是准确率刚好一样，那无所谓

**Comment by zmxnancy123** [comment]
if i % (log_interval * 20) == 0:
                t_correct = self.test(i)
                if t_correct > correct:
                    correct = t_correct
                # print('to target max correct: ', correct.item(), "\n")
        return 100. * correct / len(self.target_loader.dataset)
训练时的这段代码我的理解是一定的迭代次数后进行测试，所以我感觉是边训练边测试的，然后取最好的一次作为最终的结果。因为我想保存下训练好的模型，直接测试看看运行时间，但不知道该如何拆开。我的理解可能是有问题的，期待您的解答。
不同被试相同的结果是我在跑第一次会话时，第13、14、15个人分别当目标域时他们的准确率完全相同
Target_session_id: 12, current_subject_id: 12, acc: 98.05538940429688
Target_session_id: 13, current_subject_id: 13, acc: 98.05538940429688
Target_session_id: 14, current_subject_id: 14, acc: 98.05538940429688

**Comment by VoiceBeer** [comment]
对的确实是训练中一定步数后会有测试，然后保存结果最好的。

第二部分那边的target_session_id，session的话我记得应该是只有三个的吧，你这个target_session_id是subject_id？

**Comment by zmxnancy123** [comment]
是的是的，我的target_session_id是subject_id，和session没有关系，命名写错了。
我是在运行第一次session时出现不同的人当目标域时，准确率相同的情况。计算准确率用的是预测正确的标签数量/3394是吗，那只要不同的目标域预测值不一样，但因为正确的数量是一样的，所以造成的准确率一样是被允许的是吗？
训练中一定步数后会有测试，然后保存结果最好的，这样的测试感觉很像验证集，那也就是说我需要保存下结果最好的那次模型，然后直接测试去查看测试时间是吗？
训练时我们是提供了目标域所有的数据分布情况去进行训练，关于这一点，我的老师要求目标域不参与训练或者只提供少部分数据训练，剩下的测试，但我发现大多数代码都是目标域提供所有的数据分布，想问问关于这一点您是怎么看的。非常感谢您一直回答我的问题！

**Comment by VoiceBeer** [comment]
1. 我记得按理来说不会出现你这样连续多次的同样数值准确率的，你确定下是不是你这几个同样准确率的其实都是同一个被试。
2. 无所谓测试或者验证，保存下来的就是在单个或者平均下来的目标域上效果最好的模型。你这个拿去测试为什么要看测试时间？测试所消耗的时间的话跟模型效果无关，跟模型大小有关。
3. 领域自适应的话目标域肯定是会参与的，如果想要少部分目标域的数据的话，你可以去看下few-shot domain adapataion（不确定是不是叫这个名字）这类的；如果想要目标域不参与训练的话，那就是domain generalization。

**Comment by zmxnancy123** [comment]
我确定了一下是不同的被试，输入的特征是不同的，那么这种情况是否是因为预测正确的标签数量相同呢？

**Comment by VoiceBeer** [comment]
你可以把预测结果plot出来看看是不是都一样的

**Comment by zmxnancy123** [comment]
我输出了预测结果，是不相同的

**Comment by VoiceBeer** [comment]
这么巧吗刚好这三个虽然数字不同但算出来准确率一样，另外我看你结果里为什么有两个session id，一个是源域一个目标域？你这是同一个被试拟合自己吗

**Comment by zmxnancy123** [comment]
应该是这样的：
Target_id: 12, current_session_id: 0, acc: 98.05538940429688
Target_id: 13, current_session_id: 0, acc: 98.05538940429688
前面那个是我保存的时候没有写对。具体是我以第一次会话为例，让15个人依次当一次目标域，然后出现不同的被试当目标域时ACC相同，然后我输出了最后的预测标签，发现他们预测值是不同的，但最后预测正确的个数是相同的，所以会造成ACC一样。

**Comment by VoiceBeer** [comment]
让15个人依次当一次目标域那就是现在代码的逻辑吧？[链接在这](https://github.com/VoiceBeer/MS-MDA/blob/96f2abb359b0b6f20cf158558923080e5ee16998/msmdaer.py#L299)，你这是重写了一个？按理来说我记得现在的代码逻辑就能直接输出15个人轮流当目标域的结果的

**Comment by zmxnancy123** [comment]
对，是现在代码的逻辑，代码原本会输出15个人轮流当目标域时的平均值作为最终的准确率，我只是又单独保存了一下每个人当目标域时的结果，然后发现出现不同的被试当目标域时相同的准确率。我怀疑是我改了之后的模型有问题但输出预测标签是不同的，只是预测正确的数量相同，所以我觉得这样的情况应该是没什么问题的吧

**Comment by VoiceBeer** [comment]
应该没问题，或者你干脆重新git clone一版现在的代码，然后跑一次看看没修改前的原始模型跑出来的结果是否有这个问题

**Comment by zmxnancy123** [comment]
好的好的，非常感谢，一直在问您问题，感谢您每次耐心的回答！

**Comment by VoiceBeer** [comment]
没事没事 😸

**Comment by zmxnancy123** [comment]
作者您好，又来打扰您了，我还是想再问问关于目标域参与训练的问题，目标域参与训练只是提供数据分布，那是否应该将目标域拆开，一部分用于训练分布，另一部分测试呢？我看代码的意思是目标域全部参与训练，提供分布，然后接着用他们测试。

**Comment by VoiceBeer** [comment]
哈喽，明白你的担忧，怕测试数据泄漏。这部分你可以去知乎看看王晋东老师关于domain adaptation的解释。这其实是两种学习范式，传统的是归纳式的，这种能看到测试数据分布的是直推式学习（Indcutive learning)

**Comment by zmxnancy123** [comment]
嗨，我去看了有关直推式学习的知识，有的介绍说的是目标域提供一些未标记的数据参与测试，王晋东老师的书里有一段代码写的也是参与训练分布的目标域数据和测试的目标域数据是不一样的，我的疑惑点还是在于代码里是否可以将测试数据都去训练分布再来用这些数据测试结果。这样做的话效果肯定会比较好，但总觉得有点奇怪。

**Comment by VoiceBeer** [comment]
我也有点忘了其实。不过只要目标域的标签信息不引入的话，单纯数据分布也还好，然后因为模型看过目标的数据分布所以效果肯定会好。DA这个领域我了解不多有点把不准你可以多看看，如果你想严格一点的话可能目标域拆成验证和测试会好点？

**Comment by zmxnancy123** [comment]
好的好的，谢谢您的回复！我拆开试试看

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年12月22日 12:49 |
| 收件人 | VoiceBeer/MS-MDA ***@***.***> |
| 抄送人 | nancy ***@***.***>,
Mention ***@***.***> |
| 主题 | Re: [VoiceBeer/MS-MDA] 关于损失函数 (Issue #11) |

我也有点忘了其实。不过只要目标域的标签信息不引入的话，单纯数据分布也还好，然后因为模型看过目标的数据分布所以效果肯定会好。DA这个领域我了解不多有点把不准你可以多看看，如果你想严格一点的话可能目标域拆成验证和测试会好点？

**Comment by hongyizhi** [comment]
作者您好，请问是否可以交换一下邮箱，想和您交流一下，非常感谢

**Comment by VoiceBeer** [comment]
@hongyizhi h.c.chen@zju.edu.cn
