### ISSUE TITLE
SEED数据集的session分类问题

### ISSUE THREAD

**Issue by upeng10** [VoiceBeer/MS-MDA#12]
作者您好，您在readme里面提到seed中的extracted features文件夹中，需要按照/1/2/3这样的子目录形式，分别把3个session的数据放进去。但extracted features中的所有mat文件只标注了被试序号和时间，该去如何区分各个session呢？我这边是按照时间先后来划分不同的session的，不知道是否正确。
接上文，在没有改动任何代码的情况下，最后复现出的结果，seed数据集cross session的准确率为88%，和论文一样，但是cross subject准确率只有80%，比论文低了9-10%，所以想来咨询一下，有没有可能是我在处理数据集或者其他部分出了问题。
最后谢谢作者能看到这里，恳请您能够拨冗答疑。

**Comment by VoiceBeer** [comment]
我记得好像是按时间分的，应该没问题。至于这个代码的结果的话，你可以看一下这个issue #3。目前的代码实现是考虑loso的，论文里的则是固定的只把最后一个subject或者session当作target。

**Comment by VoiceBeer** [comment]
哈喽 问题解决了嘛 @upeng10
