### ISSUE TITLE
About Negtive transfer

### ISSUE THREAD

**Issue by fightingst** [VoiceBeer/MS-MDA#2]
您好！请问您在做脑电domain adaptation时有遇到过负迁移的现象吗？如果有的的话有什么解决思路吗？感谢

**Comment by VoiceBeer** [comment]
您好，感谢您的提问！

我在SEED和SEED-IV上暂时没碰到过负迁移的情况，一般来说哪怕是普通的DAN效果都有显著提升的。如果你确实碰到了用了DA但是效果反而更差的情况的话，可以考虑从数据的角度检查，比如是否统一了数据预处理（这里指的是进入模型之前的归一化等等方式），或者可能你的模型太过于复杂等等，具体还是从你的setting里看。不过我个人倾向于是数据预处理的问题，我印象里好像以前不做处理试过一次效果就很差。

希望对您有所帮助
