### ISSUE TITLE
标准化问题

### ISSUE THREAD

**Issue by csu-fcj** [VoiceBeer/MS-MDA#5]
作者您好，感谢您的分享。仔细拜读了您的文章，关于标准化有一个小问题希望解答。
您在文章中提出了很多标准方法运用在源域，那么对于目标域而言，是否需要标准化又是如何标准化的。此外，DA的前提似乎是需要利用所有的无标签测试集数据，这样的方法在实际应用上似乎稍显不足。

**Comment by VoiceBeer** [comment]
Hi感谢您对我们工作的关注！

对于目标域也是应用了跟源域一样的标准化方式的，如果不采用一致的标准化的话，偏差会很大。
另外您的观点也非常对，在实际情况中，确实比较少有拥有目标域数据的情况，所以在DA之上，还有Domain Generalization (DG)，即假设不存在目标域测试数据，直接在源域上操作，以达到对于下游任务更好的性能，您感兴趣的话可以去了解一下。不过如果谈到“实际使用”的话，我认为暂时没有特别好的办法。

**Comment by csu-fcj** [comment]
感谢您的回复！您的项目对迁移学习情感脑机领域具有很大的贡献。DG我也有在关注，也认为会是迁移学习脑机的未来发展方向。可惜相关资源较少。

**Comment by VoiceBeer** [comment]
Hi！确实是的，DG在这个领域我也认为是有很大的发展空间，但是DG自己本身也是在发展的，所以交叉起来确实目前还没什么特别大的进度

**Comment by csu-fcj** [comment]
作者您好，想请问一下您工作的计算时间是不是特别大，我把common feature extractor改成了GNN，发现速度特别特别慢，估摸着只有千分之一，请问您有什么建议，可能是我代码写错了吗。

**Comment by VoiceBeer** [comment]
Hi，确实是会比较慢的，因为这个是面对多个源域，所以你可以理解为对每一个源域都有一个模型。现在的CFE是普通的线性层还可以接受，如果你都改成了GNN的话，对应比如10个源域那就是模型中有10个GNN，所以肯定会变得很慢很慢

**Comment by csu-fcj** [comment]
作者您好，测试代码的时候发现
def __init__(self, pretrained=False, number_of_source=15, number_of_category=4):
...
for i in range(number_of_source):
            exec('self.DSFE' + str(i) + '=DSFE()')
            exec('self.cls_fc_DSC' + str(i) + '=nn.Linear(32,' + str(number_of_category) + ')')
其中'number_of_category=4' 应该是生成DSC这个分类器的输出层尺寸，在SEED中应该为3，在SEED4中应该为4.但我经过测试发现，无论我设置这个数值为多少，无论我设置这个数值为多少test.shape 的结果永远是[batch,3]，代码都不会报错。我的理解test.shape 应为[bacth,number_of category]
请问您能解答一下吗？
DSFE_name = 'self.DSFE' + str(i)
                DSC_name = 'self.cls_fc_DSC' + str(i)
                feature_DSFE_i = eval(DSFE_name)(data_CFE)
                test = eval(DSC_name)(feature_DSFE_i)
                print(test.shape)

**Comment by csu-fcj** [comment]
作者您好！请问您有没有print过模型的loss呢，我更改backbone为GNN后发现loss很大，进而我print了一下您原始模型的loss，发现波动也很大。但是效果却很好，我看了一下您的代码，发现是保存最好的一次epoch作为test的准确率，那这样的做法会不会导致模型实际上是随机跳到test比较好的点，然后刚好被记录下来了？下图是其中一个epoch的loss和accuracy
![image](https://user-images.githubusercontent.com/48011800/183050406-266d1e1b-b6b0-459e-bb81-adc4ef54b01a.png)

**Comment by VoiceBeer** [comment]
Hi!这部分的问题我推荐您使用tensorboard来系统性地看一些loss和acc，我个人之前是记录了总的loss和其他几个小loss，以及对应的acc，不过这些数值的变化很多其实还是比较依赖超参的选择，例如大epoch小bs波动就会合理点（取决于实际情况，这个比较看调参，之前我有一些tensorboard的记录，但是现在手头上找不到抱歉:<）。另外，关于为什么是保存最好的一次作为acc，这个的话其实算是约定俗成？大部分其他对比工作应该都是记录最好的（指导我的前辈如是说），不然我个人认为其实很难达到所谓的90%+

**Comment by zmxnancy123** [comment]
你好，我想问一下将CFE变为GNN后时间比较久的话，是否可以考虑换成双向lstm呢，我看文章说未来工作可以考虑换成lstm，是否可以这样修改呢

**Comment by VoiceBeer** [comment]
@zmxnancy123 Hi，当然可以，完全没问题，不过记得数据处理上改一下方式。lstm我记得吕宝粮老师他们组常用，但是我个人没怎么试过因此没有放进去。对于EEG这样的时序数据lstm应该会好一些

**Comment by zmxnancy123** [comment]
那换成lstm时间会不会太久了啊，还想问问数据在进入CFE前输出的格式是（128，310），整个程序的输入是（3394，310），为什么在输入前就变成（128，310）了啊，我在更改为lstm时是不是需要保持输入为（128，310）？

**Comment by VoiceBeer** [comment]
@zmxnancy123 128是一个batch的大小，3394是所有的数据，你要使用模型的话调整batch size就能改变对应batch的大小

**Comment by zmxnancy123** [comment]
啊，不好意思，我搞混了，脑子里一直记得batch设置的是256，还说为啥输出是128。感谢你的回答，我试着改成lstm看看效果。

**Comment by VoiceBeer** [comment]
@zmxnancy123 没问题，祝你好运:>
