### ISSUE TITLE
请问msmda的代码可以改成可运行的吗

### ISSUE THREAD

**Issue by zy2021314** [VoiceBeer/MS-MDA#7]
现在代码还处于
<<<<<updated upstream
=========
>>>>>>stashed changes
的修改状态，而且有些缩进是没调整好的
请问作者能给一下一开始的代码吗，我怕我复现错误。

**Comment by VoiceBeer** [comment]
Hi，目前的代码是可以运行的，issue中的问题不影响整体的复现，只会对结果有一些影响，但是我现在没有数据集的使用权限了所以没法更新。

至于缩进的话，我记得好像没有什么问题吧？不过我会现在检查一下

**Comment by VoiceBeer** [comment]
哈喽我刚更新了代码的缩进，也同步了一下历史版本，但是目前没有数据集可以使用所以没法测试。您可以按照README的介绍运行一下代码，然后对比一下跟README里的结果看看是否一致

**Comment by zy2021314** [comment]
感谢作者大大的更新！！！

**Comment by VoiceBeer** [comment]
:laughing: 没事没事
