### ISSUE TITLE
目录名无效

### ISSUE THREAD

**Issue by Qiaoyunqing** [VoiceBeer/MS-MDA#8]
作者您好，我想请教一下，为什么会一直提示NotADirectoryError: [WinError 267] 目录名称无效。: 'ExtractedFeatures/10_20131130.mat'，它读取的是一个文件，而不是目录，是因为 mats = os.listdir(path + '/' + session)这行的原因吗

**Comment by VoiceBeer** [comment]
Hello，你把数据集的文件路径改成readme里面那样的吗？也就是：
```
eeg_feature_smooth/
    1/
    2/
    3/
ExtractedFeatures/
    1/
    2/
    3/
```
这样吗？注意1，2，3分别代表对应的session，然后各个子文件夹里才是的.mat文件。

至于`mats = os.listdir(xxx)`那里只是用来得到当前文件夹下的所有文件的名字，后面才是文件的读取。

**Comment by Qiaoyunqing** [comment]
好的，谢谢作者😊

**Comment by VoiceBeer** [comment]
😆 不客气，欢迎提issue
