### ISSUE TITLE
数据集提问

### ISSUE THREAD

**Issue by zmxnancy123** [VoiceBeer/MS-MDA#9]
作者您好啊，很抱歉打扰您啦，我想问问您数据集是直接将seed里面的ExtractedFeatures按照实验分为1.2.3三个文件夹然后送入程序的吗还是需要提前处理为3394x310的形式然后分为1.2.3文件夹送入的。我刚刚开始接触这个领域，读了您的文章感觉对我很有启发，想复现一下代码，就是在读数据集的时候就一直报错，所以就想来问问您。

**Comment by VoiceBeer** [comment]
@zmxnancy123 哈喽，感谢对这个工作的关注。数据只要从官网下载好后按照readme那样分成三个文件夹就行，预处理的代码和方式都在[util.py](https://github.com/VoiceBeer/MS-MDA/blob/795189e782a42a4503cdb45c9b9852486c5a71b6/utils.py#L279)的load_data这个函数里了，然后在主文件的[这一行](https://github.com/VoiceBeer/MS-MDA/blob/795189e782a42a4503cdb45c9b9852486c5a71b6/msmdaer.py#L245)调用下就行。

**Comment by zmxnancy123** [comment]
好的好的，谢谢啦，可以跑通啦

**Comment by VoiceBeer** [comment]
okok，后续有问题的话欢迎继续提问 :D
